In [1]:
import pandas as pd

### 1. Membaca File JSON di Pandas

In [4]:
file = '../0.Dataset/salary_rice.json'
df= pd.read_json(file)
df

   id employee_name  salary_rice_kg  allowance_value_idr
0   1  Budi Santoso              10               150000
1   2    Siti Rahma              20               300000
2   3    Ahmad Dani              10               150000
3   4  Dewi Lestari              25               375000

### 2. Membaca File JSON Bersarang

In [ ]:
# Menggunakan Modul json dan metode pd.json_normalize()
import json
data = {"One": {"0": 60, "1": 60, "2": 60, "3": 45, "4": 45, "5": 60},
        "Two": {"0": 110, "1": 117, "2": 103, "3": 109, "4": 117, "5": 102}}

json_data = json.dumps(data)

df_normalize = pd.json_normalize(json.loads(json_data))
print(f"\nDataframe using Json Module and 'ps.json_normalize()'\n {df_normalize}")

df = pd.DataFrame(df_normalize)
df

Dataframe using Json Module and 'ps.json_normalize()'
    One.0  One.1  One.2  One.3  One.4  One.5  Two.0  Two.1  Two.2  Two.3  \
0     60     60     60     45     45     60    110    117    103    109

   Two.4  Two.5
0    117    102

,One.0,One.1,One.2,One.3,One.4,One.5,Two.0,Two.1,Two.2,Two.3,Two.4,Two.5
0,60,60,60,45,45,60,110,117,103,109,117,102

In [ ]:
# Menggunakan pd.DataFrame dengan Dictionary
data_json = '{"Nama": "Budi", "Usia": 25, "Kota": "Jakarta"}'

data_dict = json.loads(data_json) # Mengubah menjadi dictionary
df = pd.DataFrame([data_dict])

print(type(data_dict)) 
print(data_dict["Nama"])
df

<class 'dict'>
Budi

   Nama  Usia     Kota
0  Budi    25  Jakarta