## 1. Import Libraries and Load Cleaned Data

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler, OneHotEncoder

import warnings
warnings.filterwarnings('ignore', category=UserWarning)

In [8]:
df = pd.read_csv('dataset/EastWestAirlines_CLEANING.csv')
df.head(3)

,Balance,Qual_miles,cc1_miles,cc2_miles,cc3_miles,Bonus_miles,Bonus_trans,Flight_miles_12mo,Flight_trans_12,Days_since_enroll,Award
0,28143,0,1,1,1,174,1,0,0,7000,0
1,19244,0,1,1,1,215,2,0,0,6968,0
2,41354,0,1,1,1,4123,4,0,0,7034,0

## 2. Feature Scaling

In [10]:
num_cols = df.select_dtypes(include=np.number).columns
cat_cols = df.select_dtypes(include='object').columns
num_pipeline = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy="mean")),
    ('scaler',RobustScaler())
])
cat_pipeline = Pipeline(steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('encoder',OneHotEncoder(handle_unknown='ignore',sparse_output=False))
])
preprocessor = ColumnTransformer(transformers=[
    ('num',num_pipeline,num_cols),
    ('cat',cat_pipeline,cat_cols)
])
preprocessor.set_output(transform="pandas")
X_cleaned = preprocessor.fit_transform(df)
X_cleaned.head()

,num__Balance,num__Qual_miles,num__cc1_miles,num__cc2_miles,num__cc3_miles,num__Bonus_miles,num__Bonus_trans,num__Flight_miles_12mo,num__Flight_trans_12,num__Days_since_enroll,num__Award
0,-0.202990,0.0,0.0,0.0,0.0,-0.310672,-0.785714,0.000000,0.0,0.838994,0.0
1,-0.323457,0.0,0.0,0.0,0.0,-0.308855,-0.714286,0.000000,0.0,0.829744,0.0
2,-0.024150,0.0,0.0,0.0,0.0,-0.135634,-0.571429,0.000000,0.0,0.848822,0.0
3,-0.383941,0.0,0.0,0.0,0.0,-0.296222,-0.785714,0.000000,0.0,0.825119,0.0
4,0.739318,0.0,1.5,0.0,0.0,1.600878,1.000000,6.625199,4.0,0.820205,1.0

## 3. The Analysis K Selection in GMM