In [39]:
import pandas as pd
import numpy as np

In [40]:
df = pd.read_csv('../0.dataset/dataset_penjualan_emas_kotor.csv')
df.head(10)

,Transaction_ID,Date,Customer_ID,Gold_Type,Karat,Weight_Gram,Price_Per_Gram,Total_Price,Payment_Method,Store_Location
0,TXN-0295,2024-04-21,CUST-480,Perhiasan,24,35.55,1370210,48710965,Kartu Kredit,JKT Pusat
1,TXN-0809,2024-03-09,CUST-373,Perhiasan,18,NaN,961081,11215815,Transfer Bank,Makassar
2,TXN-0364,2024-11-18,CUST-175,Perhiasan,24,49.59,1323332,65624033,QRIS,Bandung
3,TXN-0869,2025-09-30,CUST-313,Perhiasan,24,44.73,1352769,60509357,QRIS,Makassar
4,TXN-0326,2025-03-13,CUST-158,Koin,18,10.93,960581,10499150,Transfer Bank,Surabaya
5,TXN-0304,2025-11-11,CUST-110,Koin,24,38.79,1350607,52390045,Kartu Kredit,Makassar
6,TXN-0141,00-00-2024,CUST-427,Batangan,24,34.33,1362814,46785404,QRIS,Medan
7,TXN-0681,2025-02-18,CUST-268,Batangan,18,17.91,944426,16914669,QRIS,JKT Pusat
8,TXN-0714,2025-01-24,CUST-145,Batangan,22,8.01,1148229,9197314,Transfer Bank,Surabaya
9,TXN-0225,2025-11-02,CUST-384,Batangan,24,33.08,1325974,43863219,Kartu Kredit,Bandung

In [41]:
colom_numerik = df.select_dtypes(include=np.number).columns

skewsness = df.select_dtypes(include=np.number).skew()
colom_normals = skewsness[skewsness.abs() <= 0.5].index

## 1.Normalisasi Data

### 1.Metode Min-Max Scaling

In [42]:
from sklearn.preprocessing import MinMaxScaler
df_target = df.copy()

scaler = MinMaxScaler(feature_range=(0,1))
df_target[colom_normals] = scaler.fit_transform(df_target[colom_normals])

print(f'Sesudah Minmax Scaler:\n {df_target[colom_normals].head(5)}')

Sesudah Minmax Scaler:
    Karat  Weight_Gram  Price_Per_Gram
0    1.0     0.738885        0.979265
1    0.0          NaN        0.088906
2    1.0     0.994716        0.877248
3    1.0     0.906159        0.941309
4    0.0     0.290270        0.087817

### 2.Metode MaxAbs Scaling

In [43]:
from sklearn.preprocessing import MaxAbsScaler
df_target = df.copy()

scaler = MaxAbsScaler()
df_target[colom_normals] = scaler.fit_transform(df_target[colom_normals])

print(f'Sesudah MaxAbs Scaler:\n {df_target[colom_normals].head(5)}')

Sesudah MaxAbs Scaler:
    Karat  Weight_Gram  Price_Per_Gram
0   1.00     0.712711        0.993094
1   0.75          NaN        0.696568
2   1.00     0.994186        0.959118
3   1.00     0.896752        0.980454
4   0.75     0.219126        0.696205

### 3.Metode Robust Scaling

In [44]:
from sklearn.preprocessing import RobustScaler
df_target = df.copy()

scaler = RobustScaler()
df_target[colom_numerik] = scaler.fit_transform(df_target[colom_numerik])

print(f'Sesudah Robust Scaling:\n {df_target[colom_numerik].head(5)}')

Sesudah Robust Scaling:
       Karat  Weight_Gram  Price_Per_Gram  Total_Price
0  0.333333     0.415888        0.609248     0.759467
1 -0.666667          NaN       -0.495971    -0.629988
2  0.333333     0.962617        0.482612     1.386213
3  0.333333     0.773364        0.562133     1.196679
4 -0.666667    -0.542835       -0.497322    -0.656545

### 4.Metode Vector Transformation

In [45]:
from sklearn.preprocessing import normalize
df_target = df.copy()

df_target = df_target.dropna()
df_target[colom_numerik] = normalize(df_target[colom_numerik],norm='l2') # bisa pilih l1 or l2

print(f'Sesudah Vector Trasnfrom :\n {df_target[colom_numerik].head(5)}')

Sesudah Vector Trasnfrom :
           Karat   Weight_Gram  Price_Per_Gram  Total_Price
0  4.925074e-07  7.295266e-07        0.028118     0.999605
2  3.656453e-07  7.555147e-07        0.020161     0.999797
3  3.965338e-07  7.390398e-07        0.022351     0.999750
4  1.707294e-06  1.036707e-06        0.091111     0.995841
5  4.579501e-07  7.401619e-07        0.025771     0.999668

## 2.Standardisasi Data

### 1.Metode Z-Score Standardization

In [48]:
from sklearn.preprocessing import StandardScaler
df_target = df.copy()

scaler = StandardScaler()
df_target[colom_normals] = scaler.fit_transform(df_target[colom_normals])
print(f'Sesudah Z-score Standardization :\n {df_target[colom_normals].head(5)}')

Sesudah Z-score Standardization :
       Karat  Weight_Gram  Price_Per_Gram
0  1.121651     0.740542        1.396501
1 -1.240532          NaN       -1.071479
2  1.121651     1.699596        1.113720
3  1.121651     1.367616        1.291292
4 -1.240532    -0.941220       -1.074495

### 2.Metode Mean Normalization

In [51]:
df_target = df.copy()
df_target[colom_normals] = (df_target[colom_normals]-df_target[colom_normals].mean()) / (df_target[colom_normals].max() - df_target[colom_normals].min())
df_target[colom_normals]

         Karat  Weight_Gram  Price_Per_Gram
0     0.474837     0.197542        0.503808
1    -0.525163          NaN       -0.386551
2     0.474837     0.453373        0.401790
3     0.474837     0.364816        0.465852
4    -0.525163    -0.251073       -0.387640
...        ...          ...             ...
1015  0.141503     0.186244       -0.037525
1016 -0.525163          NaN       -0.454831
1017 -0.525163     0.277899       -0.378765
1018 -0.525163     0.178591       -0.467838
1019  0.141503          NaN        0.002483

[1020 rows x 3 columns]

### 3.Unit Variance Scaling

In [53]:
from sklearn.preprocessing import StandardScaler
df_target = df.copy()

scaler = StandardScaler(with_mean=True,with_std=True)
df_target[colom_normals] = scaler.fit_transform(df_target[colom_normals])
print(f'Sesudah Z-score Standardization :\n {df_target[colom_normals].head(5)}')

Sesudah Z-score Standardization :
       Karat  Weight_Gram  Price_Per_Gram
0  1.121651     0.740542        1.396501
1 -1.240532          NaN       -1.071479
2  1.121651     1.699596        1.113720
3  1.121651     1.367616        1.291292
4 -1.240532    -0.941220       -1.074495

## 3.Transformasi Yeo-Johnson

In [55]:
skewsness = df.select_dtypes(include=np.number).skew()
colom_skew = skewsness[skewsness.abs() >= 0.5].index

In [65]:
from sklearn.preprocessing import PowerTransformer
df_target = df.copy()

pt = PowerTransformer(method='yeo-johnson')
df_target[colom_skew] = pt.fit_transform(df_target[colom_skew])

print(f'Skewsness Sebelum di Transfrom: {df[colom_skew].skew().iloc[0].round(2)}')
print(f'Skewsness Sesudah di Transfrom: {df_target[colom_skew].skew().iloc[0].round(2)}')

Skewsness Sebelum di Transfrom: 12.96
Skewsness Sesudah di Transfrom: 0.21