In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../0.dataset/dataset_karyawan_1000.csv')
df.head(10)

  ID_Karyawan Jenis_Kelamin  ... Level_Jabatan Rating_Kinerja
0    EMP-0001     Laki-laki  ...     Mid-Level           Baik
1    EMP-0002     Perempuan  ...        Senior           Baik
2    EMP-0003     Perempuan  ...        Senior    Sangat Baik
3    EMP-0004     Perempuan  ...        Junior           Baik
4    EMP-0005     Laki-laki  ...        Junior    Sangat Baik
5    EMP-0006     Laki-laki  ...        Junior          Cukup
6    EMP-0007     Laki-laki  ...        Junior           Baik
7    EMP-0008     Perempuan  ...     Mid-Level           Baik
8    EMP-0009     Perempuan  ...     Mid-Level          Cukup
9    EMP-0010     Perempuan  ...        Junior           Baik

[10 rows x 7 columns]

In [4]:
colom_kategori = df.select_dtypes(include='object').drop(columns=['ID_Karyawan']).columns

## 1.One-Hot Encoding

### 1.Simple One-Hot Encoding

In [5]:
from sklearn.preprocessing import OneHotEncoder
df_target = df.copy()

encoder = OneHotEncoder(sparse_output=False,drop=None)
encoded_features = encoder.fit_transform(df_target[colom_kategori])
encoded_df = pd.DataFrame(encoded_features,columns=encoder.get_feature_names_out(colom_kategori))

encoded_df.head(5)

   Jenis_Kelamin_Laki-laki  ...  Rating_Kinerja_Sangat Baik
0                      1.0  ...                         0.0
1                      0.0  ...                         0.0
2                      0.0  ...                         1.0
3                      0.0  ...                         0.0
4                      1.0  ...                         1.0

[5 rows x 22 columns]

### 2.One-Hot Encoding dengan Drop First

In [6]:
df_target = df.copy()

df_target = pd.get_dummies(df_target,columns=colom_kategori,dtype=int)
df_target.head()

  ID_Karyawan  ...  Rating_Kinerja_Sangat Baik
0    EMP-0001  ...                           0
1    EMP-0002  ...                           0
2    EMP-0003  ...                           1
3    EMP-0004  ...                           0
4    EMP-0005  ...                           1

[5 rows x 23 columns]

## 2.Label Encoding

### 1.Label Encoding Sederhana

In [7]:
from sklearn.preprocessing import LabelEncoder
df_target = df.copy()

label = LabelEncoder()

for col in colom_kategori:
    df_target[col] = label.fit_transform(df_target[col])

df_target[colom_kategori].head()

   Jenis_Kelamin  Departemen  ...  Level_Jabatan  Rating_Kinerja
0              0           2  ...              2               0
1              1           0  ...              3               0
2              1           4  ...              3               3
3              1           3  ...              0               0
4              0           4  ...              0               3

[5 rows x 6 columns]

### 2.Label Encoding Berdasarkan Frekuensi

In [8]:
df_target = df.copy()

for col in colom_kategori:
    frequnecy = df_target[col].value_counts()
    df_target[col] = df_target[col].map(frequnecy)

df_target[colom_kategori].head()

   Jenis_Kelamin  Departemen  ...  Level_Jabatan  Rating_Kinerja
0            559         296  ...            349             546
1            441         145  ...            168             546
2            441         258  ...            168             153
3            441         212  ...            413             546
4            559         258  ...            413             153

[5 rows x 6 columns]

## 3.Binary Encoding

### 1.Binary Encoding Sederhana

In [9]:
# pip install category_encoders

## 4.Ordinal Encoding

### 1.Ordinal Encoding Berdasarkan Urutan Logis

In [ ]:
from sklearn.preprocessing import OrdinalEncoder
colom_ordinal = ['Pendidikan_Terakhir','Level_Jabatan']
df_target = df[colom_ordinal].copy()

urutan_akademik = ['SMA/SMK','D3','S1','S2']
urutan_jabatan = ['Junior','Mid-Level','Senior','Lead/Manager']

df_target['Level_Jabatan'].unique()
encoder = OrdinalEncoder(categories=[urutan_akademik,urutan_jabatan],dtype=int)

df_target[colom_ordinal] = encoder.fit_transform(df_target[colom_ordinal])

df_target.head()

<bound method OneToOneFeatureMixin.get_feature_names_out of OrdinalEncoder(categories=[['SMA/SMK', 'D3', 'S1', 'S2'],
                           ['Junior', 'Mid-Level', 'Senior', 'Lead/Manager']],
               dtype=<class 'int'>)>