In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('../0.dataset/dataset_karyawan_1000.csv')
df.head(10)

,ID_Karyawan,Jenis_Kelamin,Departemen,Status_Pernikahan,Pendidikan_Terakhir,Level_Jabatan,Rating_Kinerja
0,EMP-0001,Laki-laki,IT,Belum Menikah,S1,Mid-Level,Baik
1,EMP-0002,Perempuan,Finance,Belum Menikah,S1,Senior,Baik
2,EMP-0003,Perempuan,Operations,Menikah,D3,Senior,Sangat Baik
3,EMP-0004,Perempuan,Marketing,Belum Menikah,S1,Junior,Baik
4,EMP-0005,Laki-laki,Operations,Belum Menikah,S1,Junior,Sangat Baik
5,EMP-0006,Laki-laki,Marketing,Menikah,S1,Junior,Cukup
6,EMP-0007,Laki-laki,Marketing,Menikah,S2,Junior,Baik
7,EMP-0008,Perempuan,Operations,Menikah,SMA/SMK,Mid-Level,Baik
8,EMP-0009,Perempuan,IT,Belum Menikah,S1,Mid-Level,Cukup
9,EMP-0010,Perempuan,Finance,Menikah,SMA/SMK,Junior,Baik

In [4]:
colom_kategori = df.select_dtypes(include='object').drop(columns=['ID_Karyawan']).columns

## 1.One-Hot Encoding

### 1.Simple One-Hot Encoding

In [16]:
from sklearn.preprocessing import OneHotEncoder
df_target = df.copy()

encoder = OneHotEncoder(sparse_output=False,drop=None)
encoded_features = encoder.fit_transform(df_target[colom_kategori])
encoded_df = pd.DataFrame(encoded_features,columns=encoder.get_feature_names_out(colom_kategori))

encoded_df.head(5)

,Jenis_Kelamin_Laki-laki,Jenis_Kelamin_Perempuan,Departemen_Finance,Departemen_HR,Departemen_IT,Departemen_Marketing,Departemen_Operations,Status_Pernikahan_Belum Menikah,Status_Pernikahan_Cerai,Status_Pernikahan_Menikah,...,Pendidikan_Terakhir_S2,Pendidikan_Terakhir_SMA/SMK,Level_Jabatan_Junior,Level_Jabatan_Lead/Manager,Level_Jabatan_Mid-Level,Level_Jabatan_Senior,Rating_Kinerja_Baik,Rating_Kinerja_Cukup,Rating_Kinerja_Kurang,Rating_Kinerja_Sangat Baik
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0