In [24]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [25]:
df = pd.read_csv('../0.dataset/dataset_penjualan_emas_kotor.csv')
df.head(5)

,Transaction_ID,Date,Customer_ID,Gold_Type,Karat,Weight_Gram,Price_Per_Gram,Total_Price,Payment_Method,Store_Location
0,TXN-0295,2024-04-21,CUST-480,Perhiasan,24,35.55,1370210,48710965,Kartu Kredit,JKT Pusat
1,TXN-0809,2024-03-09,CUST-373,Perhiasan,18,NaN,961081,11215815,Transfer Bank,Makassar
2,TXN-0364,2024-11-18,CUST-175,Perhiasan,24,49.59,1323332,65624033,QRIS,Bandung
3,TXN-0869,2025-09-30,CUST-313,Perhiasan,24,44.73,1352769,60509357,QRIS,Makassar
4,TXN-0326,2025-03-13,CUST-158,Koin,18,10.93,960581,10499150,Transfer Bank,Surabaya

In [26]:
df = df.dropna()
df.isnull().sum()

Transaction_ID    0
Date              0
Customer_ID       0
Gold_Type         0
Karat             0
Weight_Gram       0
Price_Per_Gram    0
Total_Price       0
Payment_Method    0
Store_Location    0
dtype: int64

In [27]:
df = df.drop_duplicates(keep='last')
df.duplicated().sum()

np.int64(0)

In [28]:
df = df.drop(columns=['Transaction_ID','Customer_ID','Date'])
df.head()

,Gold_Type,Karat,Weight_Gram,Price_Per_Gram,Total_Price,Payment_Method,Store_Location
0,Perhiasan,24,35.55,1370210,48710965,Kartu Kredit,JKT Pusat
2,Perhiasan,24,49.59,1323332,65624033,QRIS,Bandung
3,Perhiasan,24,44.73,1352769,60509357,QRIS,Makassar
5,Koin,24,38.79,1350607,52390045,Kartu Kredit,Makassar
6,Batangan,24,34.33,1362814,46785404,QRIS,Medan

In [29]:
colom_numeric = df.select_dtypes(include=np.number).columns
colom_categorical = df.select_dtypes(include='object').columns

In [30]:
df[colom_categorical] = df[colom_categorical].apply(lambda x:x.str.title())

In [31]:
label = LabelEncoder()
for col in colom_categorical:
    df[col] = label.fit_transform(df[col])

In [33]:
scaler = StandardScaler()
df[colom_numeric] = scaler.fit_transform(df[colom_numeric])

## 1.Feature Selection (Pemilihan Fitur)

### 1.Menghapus Fitur dengan Varians Rendah

In [36]:
from sklearn.feature_selection import VarianceThreshold
df_target = df.copy()

selector = VarianceThreshold(threshold=0.1)
selector.fit(df_target)

selected_features = df_target.columns[selector.get_support()]

df_target = df_target[selected_features]
df_target.head()

,Gold_Type,Karat,Weight_Gram,Price_Per_Gram,Total_Price,Payment_Method,Store_Location
0,2,1.117092,0.737917,1.387783,0.202386,0,2
2,2,1.117092,1.696567,1.105956,0.432261,1,0
3,2,1.117092,1.364727,1.282929,0.362745,1,3
5,1,1.117092,0.959144,1.269932,0.252390,0,3
6,0,1.117092,0.654615,1.343319,0.176215,1,4