In [16]:
import pandas as pd

## 1.Ekstraksi Fitur dari Data Waktu

In [ ]:

jumlah_baris = 20
tambahan_hari = 
data = {
    'timestamp':pd.date_range(start='2026-01-20', periods=jumlah_baris,freq='ME'),
    'value' : [i for i in range(jumlah_baris)]
}
df = pd.DataFrame(data)
df['timestamp'] = df['timestamp'] + pd.to_timedelta(tambahan_hari, unit='D')
df

    timestamp  value
0  2026-02-02      0
1  2026-03-02      1
2  2026-04-02      2
3  2026-05-02      3
4  2026-06-02      4
5  2026-07-02      5
6  2026-08-02      6
7  2026-09-02      7
8  2026-10-02      8
9  2026-11-02      9
10 2026-12-02     10
11 2027-01-02     11
12 2027-02-02     12
13 2027-03-02     13
14 2027-04-02     14
15 2027-05-02     15
16 2027-06-02     16
17 2027-07-02     17
18 2027-08-02     18
19 2027-09-02     19

### 1.Ekstraksi Fitur Berbasis Waktu (Hari, Bulan, Tahun)

In [19]:
df_target = df.copy()

df_target['day'] = df_target['timestamp'].dt.day
df_target['month'] = df_target['timestamp'].dt.month
df_target['year'] = df_target['timestamp'].dt.year

df_target.head()

            timestamp  day  month  year
0 2025-01-01 08:30:00    1      1  2025
1 2025-04-02 09:45:00    2      4  2025
2 2025-01-03 10:15:00    3      1  2025
3 2025-03-04 11:00:00    4      3  2025
4 2025-01-05 13:20:00    5      1  2025

### 2.Ekstraksi Fitur Tren

In [49]:
df_target = df.copy()
df_target['trend'] = df_target['value'].rolling(window=3).mean()
df_target['trend'] = df_target['trend'].fillna(0)
df_target.head()

   timestamp  value  trend
0 2025-01-31      0    0.0
1 2025-02-28      1    0.0
2 2025-03-31      2    1.0
3 2025-04-30      3    2.0
4 2025-05-31      4    3.0

### 3.Ekstraksi Fitur Hari Libur

In [52]:
from holidays import Indonesia

id_holidays = Indonesia()
df_target = df.copy()
df_target['is_holiday'] = df_target['timestamp'].dt.date.isin(id_holidays)
df_target

    timestamp  value  is_holiday
0  2025-01-31      0       False
1  2025-02-28      1       False
2  2025-03-31      2       False
3  2025-04-30      3       False
4  2025-05-31      4       False
5  2025-06-30      5       False
6  2025-07-31      6       False
7  2025-08-31      7       False
8  2025-09-30      8       False
9  2025-10-31      9       False
10 2025-11-30     10       False
11 2025-12-31     11       False
12 2026-01-31     12       False
13 2026-02-28     13       False
14 2026-03-31     14       False
15 2026-04-30     15       False
16 2026-05-31     16       False
17 2026-06-30     17       False
18 2026-07-31     18       False
19 2026-08-31     19       False